# Generated by Django 4.0.2 on 2022-03-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstNameFarmer', models.CharField(max_length=30)),
                ('lastNameFarmer', models.TextField()),
                ('phoneFarmer', models.BigIntegerField()),
                ('emailFarmer', models.EmailField(max_length=254)),
                ('adressFarmer', models.TextField()),
            ],
            options={
                'db_table': 'table_farmer',
            },
        ),
    ]
