# Generated by Django 3.2.7 on 2022-03-16 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointCollection', '0004_alter_pointcollection_id'),
        ('command_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command_client',
            name='point_collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pointCollection.pointcollection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='command_client',
            name='tarification',
            field=models.FloatField(default=0),
        ),
    ]
