# Generated by Django 3.2.7 on 2022-03-16 02:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_imageproduct'),
        ('command_client', '0003_alter_command_client_tarification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='article',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='quantite',
        ),
        migrations.AddField(
            model_name='panier',
            name='date_ajout',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Article_vendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_client.panier')),
            ],
        ),
    ]
