# Generated by Django 4.0.3 on 2022-03-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstNameDeliverer', models.CharField(max_length=30)),
                ('lasteNameDeliverer', models.TextField()),
                ('phoneDeliverer', models.BigIntegerField()),
                ('emailDeliverer', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'table_deliveryMan',
            },
        ),
    ]
