# Generated by Django 4.0.3 on 2022-03-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delevryMan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryman',
            old_name='lasteNameDeliverer',
            new_name='lastNameDeliverer',
        ),
    ]
