# Generated by Django 4.0.2 on 2022-03-15 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9e73c96-0bda-427a-97f9-b357ef7af1a7'), primary_key=True, serialize=False),
        ),
    ]
