# Generated by Django 3.2.7 on 2022-03-16 00:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('25cbff25-687b-4490-a53c-46cc8fd53368'), primary_key=True, serialize=False),
        ),
    ]
