# Generated by Django 3.2.7 on 2022-03-16 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ca914cb-9393-40f6-92e2-8f465f4623aa'), primary_key=True, serialize=False),
        ),
    ]
