# Generated by Django 3.2.7 on 2022-03-16 02:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b9687485-54e2-49ce-9904-ccab7ce04a2d'), primary_key=True, serialize=False),
        ),
    ]
