# Generated by Django 3.2.7 on 2022-03-16 02:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2eb49f44-b6ef-4357-9c29-65d1b58a4616'), primary_key=True, serialize=False),
        ),
    ]
