# Generated by Django 3.2.7 on 2022-03-16 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ebff34b-cd84-4bd9-8dbd-6f5970123619'), primary_key=True, serialize=False),
        ),
    ]
