# Generated by Django 3.2.7 on 2022-03-16 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c5b9730-65d9-434b-b980-bc3ccf9fbd2d'), primary_key=True, serialize=False),
        ),
    ]
