# Generated by Django 3.2.7 on 2022-03-16 02:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ffd30c6-9458-4f3d-a11b-cff32839f147'), primary_key=True, serialize=False),
        ),
    ]
