# Generated by Django 3.2.7 on 2022-03-16 02:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ddee2876-74a0-463d-81ef-a3f6159d5cdd'), primary_key=True, serialize=False),
        ),
    ]
