# Generated by Django 3.2.7 on 2022-03-16 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b148e271-c652-4e08-ac36-bdef0eeebbbc'), primary_key=True, serialize=False),
        ),
    ]
